### ISSUE TITLE
No more images displayed in feed

### ISSUE THREAD

**Issue by operatorone** [codefog/contao-instagram#42]
Hi, since some days images are not shown anymore after importing them from Instagram. See here https://www.heiserimkerei.de/ueber-uns/instagram.html

Instagram changed the image format to HEIC, which the importer is not recognizing. In the source code is only an empty img tag visible. 

Is there a way I can work around this or is there a fix already?

**Comment by fritzmg** [comment]
You can let the image be transformed by Contao (if your environment supports HEIC):

```yaml
# config/config.yaml
contao:
    image:
        sizes:
            instagram:
                formats:
                    heic: [jpg]
```

Or to also provide WebP for all formats:

```yaml
contao:
    image:
        sizes:
            instagram:
                formats:
                    gif: [webp, gif]
                    jpg: [webp, jpg]
                    jpeg: [webp, jpeg]
                    webp: [webp, jpg]
                    png: [webp, jpg]
                    heic: [webp, jpg]
```
